[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  PRISMA_GENERATE_IN_POSTBUILD = "true"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]
  timeout = "30"

[context.production]
  [context.production.environment]
    NODE_ENV = "production"